import { Inter } from "next/font/google";
import "./globals.css";
import SidebarMenu from '../components/custom/SidebarMenu'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex w-full h-full space-x-6`}>
      <SidebarMenu />
      <div className="w-[20%]"></div>
      <main className="w-[80%] h-full py-6">{children}</main>
      </body>
    </html>
  );
}
