import { Inter } from "next/font/google";
import "./globals.css";
import SidebarMenu from '../components/custom/SidebarMenu'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-screen grid grid-cols-10 gap-6 mt-4 px-6 overflow-hidden`}>
      <SidebarMenu />
      {/* <div className="w-[20%]"></div> */}
      <main className="col-span-8 h-full overflow-y-scroll hide-scrollbar">{children}</main>
      </body>
    </html>
  );
}
